// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Detect environment
const isDev = process.env.NODE_ENV !== "production";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: isDev 
      ? "ts-node prisma/seed.ts" 
      : "node dist/prisma/seed.js",
  },
  datasource: {
    url: isDev ? env("DATABASE_URL") : (process.env.DATABASE_URL || ""),
  },
});
